### ISSUE TITLE
a question of loss.py

### ISSUE THREAD

**Issue by Yinpenguin** [1991viet/Yolo-pytorch#3]
Hello! Thanks for your code! when I read the file "loss.py", I can not understand the function "bbox_ious(boxes1, boxes2)". 
Fox example, iou_gt_pred = bbox_ious(gt, cur_pred_boxes)   , we konw len(pred_boxes) is "self.num_anchors * height * width)", but we can not konw the lenth of  "groud truth boxes". So, how can we compute the IoU of them ? Thank you.

**Comment by 1991viet** [comment]
Hi,
I guess you understand it already. Given 2 sets of boxes with shape of (Nx4) and (Mx4) respectively, the IoU output will have shape of (NxM)
Bests,

**Comment by Yinpenguin** [comment]
OK, I see, thank you. @1991viet
