### ISSUE TITLE
A problem when i run train_coco.py

### ISSUE THREAD

**Issue by ustcerman** [1991viet/Yolo-pytorch#8]
Excuse me, I run the run train_coco.py, I want to train the network from the start, but i have the problem ''No such file or directory: 'trained_models/whole_model_trained_yolo_coco'', it means i have to download the pre_trained_model first? Thank you!

**Comment by 1991viet** [comment]
Yes, I already provided the link to all pre-trained models.
But, you could also train your model from the beginning without using any pre-trained model, by comment the section from line 70 to 81, and replace this section by a single line *model = Yolo(training_set.num_classes)*. It still converges, although a bit slower than when you use pre-trained-models.
Bests,

**Comment by ustcerman** [comment]
> Yes, I already provided the link to all pre-trained models.
> But, you could also train your model from the beginning without using any pre-trained model, by comment the section from line 70 to 81, and replace this section by a single line
> **model = Yolo(training_set.num_classes)**
> It still converges, although a bit slower than when you use pre-trained-models.
> Bests,

Ok，Thank You！
