### ISSUE TITLE
about GPU

### ISSUE THREAD

**Issue by pengfeidip** [1991viet/Yolo-pytorch#9]
hi
Are you training the network only on 1080ti, or  1080ti and quadro 6000 24GB ?  I only have a 1070ti 8GB , is it enough to train a YOLO v2?

**Comment by 1991viet** [comment]
Hi,
I have 2 gpus and when I run experiments, I used one of them. Your gpu is enough, for sure :)

**Comment by pengfeidip** [comment]
Thank you!
